version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs-dev
    working_dir: /application
    volumes:
      - ./application:/application
      - /application/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev
